### ISSUE TITLE
Close Keyboard after sending feedback

### ISSUE THREAD

**Issue by ishir21** [CerritusCodersComm/eduJam#47]
In the feedback section , after the user clicks on submit feedback the keyboard remains open .
The keyboard should gone after the user clicks on submit feedback.

Hint:
You can find the required function to close the keyboard from here:
https://github.com/CerritusCodersComm/eduJam/blob/main/app/src/main/java/com/example/gdsc_hackathon/extensions/FragmentExtensions.kt
call this function in the required places in the following file:
https://github.com/CerritusCodersComm/eduJam/blob/main/app/src/main/java/com/example/gdsc_hackathon/fragments/FeedbackFragment.kt

**Comment by igpapadi** [comment]
Hello! I would like to give it a try! Could you assign this to me?

**Comment by cdhiraj40** [comment]
> Hello! I would like to give it a try! Could you assign this to me?

sure! you have been assigned :)

**Comment by anamansari062** [comment]
> Could I have some somple e-mail to try the app? I have no access because it says 'Please use College E-mail'. Thanks a lot!
email : test@email.com
password : eduJam

**Comment by cdhiraj40** [comment]
could you add this mail-in readme somewhere near [here](https://github.com/CerritusCodersComm/eduJam#%EF%B8%8F-installation-steps?)@anamansari062

**Comment by cdhiraj40** [comment]
> > Could I have some somple e-mail to try the app? I have no access because it says 'Please use College E-mail'. Thanks a lot!
> 
> email : [test@email.com](mailto:test@email.com) password : eduJam


could you add this mail-in readme somewhere near [here](https://github.com/CerritusCodersComm/eduJam#%EF%B8%8F-installation-steps?)@anamansari062

**Comment by anamansari062** [comment]
@cdhiraj40 Already Did!

**Comment by cdhiraj40** [comment]
> Are you sure this is working? It still does not allow me to sign in.
> 
> ![image](https://user-images.githubusercontent.com/43881975/153908194-ae1e0da0-f75a-48bd-802d-a70d07240fcb.png)

I think it won't still let you get in because we are using a static checker for college mail. Could you send me your mail i will send you the credentials :)

**Comment by igpapadi** [comment]
> > Are you sure this is working? It still does not allow me to sign in.
> > ![image](https://user-images.githubusercontent.com/43881975/153908194-ae1e0da0-f75a-48bd-802d-a70d07240fcb.png)
> 
> Sorry it is [test@tcetmumbai.in](mailto:test@tcetmumbai.in)

I still cannot sign in, because of the password.

![image](https://user-images.githubusercontent.com/43881975/153912587-40a32b8e-b132-4497-adc1-f6914945af34.png)

**Comment by anamansari062** [comment]
@igpapadi Ig then there is some problem with the credential
You can use this for the time being
email - 1032200204@tcetmumbai.in
password - eduJam123
